[package]
name = "javelin"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[build]
rustflags = ["-C", "target-cpu=native", "-C", "vectorize-loops", "-C", "vectorize-slp"]

[dependencies]
colored = "*"
rand = "0.8"
once_cell = "1.10.0"
arrayvec = "0.7.4"