[package]
name = "javelin"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "*"
rand = "0.8"
once_cell = "1.10.0" 
arrayvec = "0.7.4"