[package]
name = "trainer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.15.0"
bytemuck = "1.5"
rand = "0.6.0"
rayon = "1.10"
javelin = { path = "../" }
datagen = { path = "../datagen/" }